### ISSUE TITLE
Identify requirements of the issue #1574

### ISSUE THREAD

**Issue by myhelmisaari** [myhelmisaari/javaparser#2]
What requirments is it for the issue we have chosen? These requirments will be used to create a project plan to test them.

Issue: https://github.com/javaparser/javaparser/issues/1574

**Comment by Mathiponds** [comment]
There are multiple problems but maybe they are related : 
* When we try to get all the comment of a java file, if the first comment is on the first line and therefore before the package declaration, this comment is not in the list returned by `cu.getAllContainedComments()` or by `cu.getComments()` doesn't contain the first comment. However the function `cu.getComment()` find the first comment.
* To relate that to our issue, I think that the fact that the comments before package declaration are not removed is because the comments are not found
* Also when we are asking about the package declaration with `cu.getPackageDeclaration()`, if there are more than one comments before the package declaration, the function return the last comment with the package declaration 
* All what I say here can be found in the commit b26956dc160b4cf3c586c80601cafbf93729e98f

**Comment by Mathiponds** [comment]
In fact, `getAllContainedComments` should not return the comment associated to the root node. So this method is right.
However, `getComments` should return this comment and this is where we sould change something and do something so that it returns all the contained comments and the comment associated to the root
