### ISSUE TITLE
Make Tests for issue #1574

### ISSUE THREAD

**Issue by Mathiponds** [myhelmisaari/javaparser#8]
For the moment we have just tried to find why the comment before the package was not added but we didn't look at the removing part 
So we should do some tests that given a file with comments before package don't have this comment anymore

**Comment by axelkennedal** [comment]
From what I can see there is already a lot of tests for issue #1574 in `src/test/java/com/github/javaparser/symbolsolver/Issue1574Test.java`. Specifically the tests `getAllCommentBeforePackageDeclarationLine()` and `getAllCommentBeforePackageDeclarationBlock()` do already test that `cu.getComments()` returns the comments before a package declaration.

Testing deletion isn't really necessary since the `comment.remove()` function isn't the function we are modifying or testing. We will assume that `remove()` works as intended and is tested elsewhere (as it should be). With this assumption it is trivial that:

```java
CompilationUnit cu = JavaParser.parse(projectDir); // projectDir is received from parameter
for (Comment child : cu.getComments()) { child.remove(); }
```
... will remove all comments, including the ones before package declarations.
